


server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    #active: native # for local
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MentalCoder91/ms-configserver.git
          default-label: main # branch name
          timeout: 5
          clone-on-start: true # please try to clone git repo in local at startup
          force-pull: true # always read from git 
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
    ssl:
      enabled: true
encrypt:
  key: "bc042739edbe3a42028cfa408bd6b77d3343ad89494b9621e96b768d3828fba1"  # check postman for encrypt and decrypt. The config server usees this cipher key to encryt it exposes 2 endpoints at 8071 check postman
      
#        native:
#          #search-locations: "classpath:/config"E:\Microservices\eazybytes\config # inside classpath
#          search-locations: "file///:E://Microservice//eazybytes//config"  # inside local file system



